# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assosiative',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('form_name', models.CharField(unique=True, max_length=100)),
                ('form_description', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('short_text1', models.BooleanField(default=False)),
                ('short_text2', models.BooleanField(default=False)),
                ('short_text3', models.BooleanField(default=False)),
                ('short_text4', models.BooleanField(default=False)),
                ('short_text5', models.BooleanField(default=False)),
                ('short_text6', models.BooleanField(default=False)),
                ('short_text7', models.BooleanField(default=False)),
                ('short_text8', models.BooleanField(default=False)),
                ('short_text9', models.BooleanField(default=False)),
                ('short_text10', models.BooleanField(default=False)),
                ('short_text11', models.BooleanField(default=False)),
                ('short_text12', models.BooleanField(default=False)),
                ('short_text13', models.BooleanField(default=False)),
                ('short_text14', models.BooleanField(default=False)),
                ('short_text15', models.BooleanField(default=False)),
                ('short_text16', models.BooleanField(default=False)),
                ('short_text17', models.BooleanField(default=False)),
                ('short_text18', models.BooleanField(default=False)),
                ('short_text19', models.BooleanField(default=False)),
                ('short_text20', models.BooleanField(default=False)),
                ('short_text21', models.BooleanField(default=False)),
                ('short_text22', models.BooleanField(default=False)),
                ('short_text23', models.BooleanField(default=False)),
                ('short_text24', models.BooleanField(default=False)),
                ('short_text25', models.BooleanField(default=False)),
                ('short_text26', models.BooleanField(default=False)),
                ('short_text27', models.BooleanField(default=False)),
                ('short_text28', models.BooleanField(default=False)),
                ('short_text29', models.BooleanField(default=False)),
                ('short_text30', models.BooleanField(default=False)),
                ('short_text31', models.BooleanField(default=False)),
                ('short_text32', models.BooleanField(default=False)),
                ('short_text33', models.BooleanField(default=False)),
                ('short_text34', models.BooleanField(default=False)),
                ('short_text35', models.BooleanField(default=False)),
                ('short_text36', models.BooleanField(default=False)),
                ('short_text37', models.BooleanField(default=False)),
                ('short_text38', models.BooleanField(default=False)),
                ('short_text39', models.BooleanField(default=False)),
                ('short_text40', models.BooleanField(default=False)),
                ('num_field1', models.BooleanField(default=False)),
                ('num_field2', models.BooleanField(default=False)),
                ('num_field3', models.BooleanField(default=False)),
                ('num_field4', models.BooleanField(default=False)),
                ('num_field5', models.BooleanField(default=False)),
                ('num_field6', models.BooleanField(default=False)),
                ('num_field7', models.BooleanField(default=False)),
                ('num_field8', models.BooleanField(default=False)),
                ('num_field9', models.BooleanField(default=False)),
                ('num_field10', models.BooleanField(default=False)),
                ('long_text1', models.BooleanField(default=False)),
                ('long_text2', models.BooleanField(default=False)),
                ('long_text3', models.BooleanField(default=False)),
                ('long_text4', models.BooleanField(default=False)),
                ('long_text5', models.BooleanField(default=False)),
                ('long_text6', models.BooleanField(default=False)),
                ('long_text7', models.BooleanField(default=False)),
                ('long_text8', models.BooleanField(default=False)),
                ('long_text9', models.BooleanField(default=False)),
                ('long_text10', models.BooleanField(default=False)),
                ('long_text11', models.BooleanField(default=False)),
                ('long_text12', models.BooleanField(default=False)),
                ('long_text13', models.BooleanField(default=False)),
                ('long_text14', models.BooleanField(default=False)),
                ('long_text15', models.BooleanField(default=False)),
                ('long_text16', models.BooleanField(default=False)),
                ('long_text17', models.BooleanField(default=False)),
                ('long_text18', models.BooleanField(default=False)),
                ('long_text19', models.BooleanField(default=False)),
                ('long_text20', models.BooleanField(default=False)),
                ('image_field1', models.BooleanField(default=False)),
                ('image_field2', models.BooleanField(default=False)),
                ('image_field3', models.BooleanField(default=False)),
                ('image_field4', models.BooleanField(default=False)),
                ('image_field5', models.BooleanField(default=False)),
                ('date_field1', models.BooleanField(default=False)),
                ('date_field2', models.BooleanField(default=False)),
                ('date_field3', models.BooleanField(default=False)),
                ('date_field4', models.BooleanField(default=False)),
                ('date_field5', models.BooleanField(default=False)),
                ('time_stamp', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Select Form Fields',
                'verbose_name_plural': 'Select Form Fields',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Contact Messages',
            },
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('slug', models.SlugField(unique=True)),
                ('short_text1', models.CharField(max_length=150, null=True, blank=True)),
                ('short_text2', models.CharField(max_length=150, null=True, blank=True)),
                ('short_text3', models.CharField(max_length=150, null=True, blank=True)),
                ('short_text4', models.CharField(max_length=150, null=True, blank=True)),
                ('short_text5', models.CharField(max_length=150, null=True, blank=True)),
                ('short_text6', models.CharField(max_length=150, null=True, blank=True)),
                ('short_text7', models.CharField(max_length=150, null=True, blank=True)),
                ('short_text8', models.CharField(max_length=150, null=True, blank=True)),
                ('short_text9', models.CharField(max_length=150, null=True, blank=True)),
                ('short_text10', models.CharField(max_length=150, null=True, blank=True)),
                ('short_text11', models.CharField(max_length=150, null=True, blank=True)),
                ('short_text12', models.CharField(max_length=150, null=True, blank=True)),
                ('short_text13', models.CharField(max_length=150, null=True, blank=True)),
                ('short_text14', models.CharField(max_length=150, null=True, blank=True)),
                ('short_text15', models.CharField(max_length=150, null=True, blank=True)),
                ('short_text16', models.CharField(max_length=150, null=True, blank=True)),
                ('short_text17', models.CharField(max_length=150, null=True, blank=True)),
                ('short_text18', models.CharField(max_length=150, null=True, blank=True)),
                ('short_text19', models.CharField(max_length=150, null=True, blank=True)),
                ('short_text20', models.CharField(max_length=150, null=True, blank=True)),
                ('short_text21', models.CharField(max_length=150, null=True, blank=True)),
                ('short_text22', models.CharField(max_length=150, null=True, blank=True)),
                ('short_text23', models.CharField(max_length=150, null=True, blank=True)),
                ('short_text24', models.CharField(max_length=150, null=True, blank=True)),
                ('short_text25', models.CharField(max_length=150, null=True, blank=True)),
                ('short_text26', models.CharField(max_length=150, null=True, blank=True)),
                ('short_text27', models.CharField(max_length=150, null=True, blank=True)),
                ('short_text28', models.CharField(max_length=150, null=True, blank=True)),
                ('short_text29', models.CharField(max_length=150, null=True, blank=True)),
                ('short_text30', models.CharField(max_length=150, null=True, blank=True)),
                ('short_text31', models.CharField(max_length=150, null=True, blank=True)),
                ('short_text32', models.CharField(max_length=150, null=True, blank=True)),
                ('short_text33', models.CharField(max_length=150, null=True, blank=True)),
                ('short_text34', models.CharField(max_length=150, null=True, blank=True)),
                ('short_text35', models.CharField(max_length=150, null=True, blank=True)),
                ('short_text36', models.CharField(max_length=150, null=True, blank=True)),
                ('short_text37', models.CharField(max_length=150, null=True, blank=True)),
                ('short_text38', models.CharField(max_length=150, null=True, blank=True)),
                ('short_text39', models.CharField(max_length=150, null=True, blank=True)),
                ('short_text40', models.CharField(max_length=150, null=True, blank=True)),
                ('num_field1', models.CharField(max_length=150, null=True, blank=True)),
                ('num_field2', models.CharField(max_length=150, null=True, blank=True)),
                ('num_field3', models.CharField(max_length=150, null=True, blank=True)),
                ('num_field4', models.CharField(max_length=150, null=True, blank=True)),
                ('num_field5', models.CharField(max_length=150, null=True, blank=True)),
                ('num_field6', models.CharField(max_length=150, null=True, blank=True)),
                ('num_field7', models.CharField(max_length=150, null=True, blank=True)),
                ('num_field8', models.CharField(max_length=150, null=True, blank=True)),
                ('num_field9', models.CharField(max_length=150, null=True, blank=True)),
                ('num_field10', models.CharField(max_length=150, null=True, blank=True)),
                ('long_text1', models.CharField(max_length=150, null=True, blank=True)),
                ('long_text2', models.CharField(max_length=150, null=True, blank=True)),
                ('long_text3', models.CharField(max_length=150, null=True, blank=True)),
                ('long_text4', models.CharField(max_length=150, null=True, blank=True)),
                ('long_text5', models.CharField(max_length=150, null=True, blank=True)),
                ('long_text6', models.CharField(max_length=150, null=True, blank=True)),
                ('long_text7', models.CharField(max_length=150, null=True, blank=True)),
                ('long_text8', models.CharField(max_length=150, null=True, blank=True)),
                ('long_text9', models.CharField(max_length=150, null=True, blank=True)),
                ('long_text10', models.CharField(max_length=150, null=True, blank=True)),
                ('long_text11', models.CharField(max_length=150, null=True, blank=True)),
                ('long_text12', models.CharField(max_length=150, null=True, blank=True)),
                ('long_text13', models.CharField(max_length=150, null=True, blank=True)),
                ('long_text14', models.CharField(max_length=150, null=True, blank=True)),
                ('long_text15', models.CharField(max_length=150, null=True, blank=True)),
                ('long_text16', models.CharField(max_length=150, null=True, blank=True)),
                ('long_text17', models.CharField(max_length=150, null=True, blank=True)),
                ('long_text18', models.CharField(max_length=150, null=True, blank=True)),
                ('long_text19', models.CharField(max_length=150, null=True, blank=True)),
                ('long_text20', models.CharField(max_length=150, null=True, blank=True)),
                ('image_field1', models.CharField(max_length=150, null=True, blank=True)),
                ('image_field2', models.CharField(max_length=150, null=True, blank=True)),
                ('image_field3', models.CharField(max_length=150, null=True, blank=True)),
                ('image_field4', models.CharField(max_length=150, null=True, blank=True)),
                ('image_field5', models.CharField(max_length=150, null=True, blank=True)),
                ('date_field1', models.CharField(max_length=150, null=True, blank=True)),
                ('date_field2', models.CharField(max_length=150, null=True, blank=True)),
                ('date_field3', models.CharField(max_length=150, null=True, blank=True)),
                ('date_field4', models.CharField(max_length=150, null=True, blank=True)),
                ('date_field5', models.CharField(max_length=150, null=True, blank=True)),
                ('time_stamp', models.DateTimeField(auto_now=True)),
                ('assosiative', models.OneToOneField(to='dyna_forms.Assosiative')),
            ],
            options={
                'verbose_name': 'Input Field Labels',
                'verbose_name_plural': 'Input Field Labels',
            },
        ),
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('short_text1', models.CharField(max_length=100, null=True, blank=True)),
                ('short_text2', models.CharField(max_length=100, null=True, blank=True)),
                ('short_text3', models.CharField(max_length=100, null=True, blank=True)),
                ('short_text4', models.CharField(max_length=100, null=True, blank=True)),
                ('short_text5', models.CharField(max_length=100, null=True, blank=True)),
                ('short_text6', models.CharField(max_length=100, null=True, blank=True)),
                ('short_text7', models.CharField(max_length=100, null=True, blank=True)),
                ('short_text8', models.CharField(max_length=100, null=True, blank=True)),
                ('short_text9', models.CharField(max_length=100, null=True, blank=True)),
                ('short_text10', models.CharField(max_length=100, null=True, blank=True)),
                ('short_text11', models.CharField(max_length=100, null=True, blank=True)),
                ('short_text12', models.CharField(max_length=100, null=True, blank=True)),
                ('short_text13', models.CharField(max_length=100, null=True, blank=True)),
                ('short_text14', models.CharField(max_length=100, null=True, blank=True)),
                ('short_text15', models.CharField(max_length=100, null=True, blank=True)),
                ('short_text16', models.CharField(max_length=100, null=True, blank=True)),
                ('short_text17', models.CharField(max_length=100, null=True, blank=True)),
                ('short_text18', models.CharField(max_length=100, null=True, blank=True)),
                ('short_text19', models.CharField(max_length=100, null=True, blank=True)),
                ('short_text20', models.CharField(max_length=100, null=True, blank=True)),
                ('short_text21', models.CharField(max_length=100, null=True, blank=True)),
                ('short_text22', models.CharField(max_length=100, null=True, blank=True)),
                ('short_text23', models.CharField(max_length=100, null=True, blank=True)),
                ('short_text24', models.CharField(max_length=100, null=True, blank=True)),
                ('short_text25', models.CharField(max_length=100, null=True, blank=True)),
                ('short_text26', models.CharField(max_length=100, null=True, blank=True)),
                ('short_text27', models.CharField(max_length=100, null=True, blank=True)),
                ('short_text28', models.CharField(max_length=100, null=True, blank=True)),
                ('short_text29', models.CharField(max_length=100, null=True, blank=True)),
                ('short_text30', models.CharField(max_length=100, null=True, blank=True)),
                ('short_text31', models.CharField(max_length=100, null=True, blank=True)),
                ('short_text32', models.CharField(max_length=100, null=True, blank=True)),
                ('short_text33', models.CharField(max_length=100, null=True, blank=True)),
                ('short_text34', models.CharField(max_length=100, null=True, blank=True)),
                ('short_text35', models.CharField(max_length=100, null=True, blank=True)),
                ('short_text36', models.CharField(max_length=100, null=True, blank=True)),
                ('short_text37', models.CharField(max_length=100, null=True, blank=True)),
                ('short_text38', models.CharField(max_length=100, null=True, blank=True)),
                ('short_text39', models.CharField(max_length=100, null=True, blank=True)),
                ('short_text40', models.CharField(max_length=100, null=True, blank=True)),
                ('num_field1', models.IntegerField(null=True, blank=True)),
                ('num_field2', models.IntegerField(null=True, blank=True)),
                ('num_field3', models.IntegerField(null=True, blank=True)),
                ('num_field4', models.IntegerField(null=True, blank=True)),
                ('num_field5', models.IntegerField(null=True, blank=True)),
                ('num_field6', models.IntegerField(null=True, blank=True)),
                ('num_field7', models.IntegerField(null=True, blank=True)),
                ('num_field8', models.IntegerField(null=True, blank=True)),
                ('num_field9', models.IntegerField(null=True, blank=True)),
                ('num_field10', models.IntegerField(null=True, blank=True)),
                ('long_text1', models.TextField(max_length=500, null=True, blank=True)),
                ('long_text2', models.TextField(max_length=500, null=True, blank=True)),
                ('long_text3', models.TextField(max_length=500, null=True, blank=True)),
                ('long_text4', models.TextField(max_length=500, null=True, blank=True)),
                ('long_text5', models.TextField(max_length=500, null=True, blank=True)),
                ('long_text6', models.TextField(max_length=500, null=True, blank=True)),
                ('long_text7', models.TextField(max_length=500, null=True, blank=True)),
                ('long_text8', models.TextField(max_length=500, null=True, blank=True)),
                ('long_text9', models.TextField(max_length=500, null=True, blank=True)),
                ('long_text10', models.TextField(max_length=500, null=True, blank=True)),
                ('long_text11', models.TextField(max_length=500, null=True, blank=True)),
                ('long_text12', models.TextField(max_length=500, null=True, blank=True)),
                ('long_text13', models.TextField(max_length=500, null=True, blank=True)),
                ('long_text14', models.TextField(max_length=500, null=True, blank=True)),
                ('long_text15', models.TextField(max_length=500, null=True, blank=True)),
                ('long_text16', models.TextField(max_length=500, null=True, blank=True)),
                ('long_text17', models.TextField(max_length=500, null=True, blank=True)),
                ('long_text18', models.TextField(max_length=500, null=True, blank=True)),
                ('long_text19', models.TextField(max_length=500, null=True, blank=True)),
                ('long_text20', models.TextField(max_length=500, null=True, blank=True)),
                ('image_field1', models.ImageField(null=True, upload_to=b'imgs', blank=True)),
                ('image_field2', models.ImageField(null=True, upload_to=b'imgs', blank=True)),
                ('image_field3', models.ImageField(null=True, upload_to=b'imgs', blank=True)),
                ('image_field4', models.ImageField(null=True, upload_to=b'imgs', blank=True)),
                ('image_field5', models.ImageField(null=True, upload_to=b'imgs', blank=True)),
                ('date_field1', models.DateField(null=True, blank=True)),
                ('date_field2', models.DateField(null=True, blank=True)),
                ('date_field3', models.DateField(null=True, blank=True)),
                ('date_field4', models.DateField(null=True, blank=True)),
                ('date_field5', models.DateField(null=True, blank=True)),
                ('time_stamp', models.DateTimeField(auto_now=True)),
                ('label', models.ForeignKey(to='dyna_forms.Label')),
            ],
            options={
                'verbose_name': 'Saved Data for individual Forms',
                'verbose_name_plural': 'Saved Data for individual Forms',
            },
        ),
    ]
